### GENERAL SETTINGS ###

# Site settings
title: Rise of Kingdom maps
description: "Rise of Kingdom maps, from Imperium and A seed kingdoms, KvK, Heroic Anthem, March of Age "
analytics: G-JQR1YEY44M #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/maps_rok" #important: start with /
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
future: true

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: discord
    url: Lysm#8681

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Z3
    - New Horizon
    - 1164 kingdom
email: hello@solidtheme.com
tel: 


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Kingdoms
    img: kingdom.jpg
    url: /kingdoms
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
  - name: KvK1&2
    img: kvk1.jpg
    url: /KvK1
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
  - name: Light&Darkness
    img: KvKLD.png
    url: /lightdarkness
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
  - name: SoC HA
    img: KvKHA.png
    url: /HA
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
  - name: SoC So8
    img: KvKSo8.jpg
    url: /So8
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
  - name: SoC MotA
    img: KvKMoA.jpg
    url: /MotA
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
  - name: SoC Desert of conquest
    img: desert.png
    url: /DoC
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Personal project, aims to build and gather full kingdom maps of rise of Kingdom. All maps are under copyright, do not use them for anything other than personnal purpose."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "You don't find your kingdom, or you want to share new ideas? Please contact me at :"
    author: discord - Lysm#8681
    position: RoK player
